import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { LogOut } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { getEmployeeStatus } from '../services/api';

export default function EmployeeDashboard() {
  const { user, logout } = useAuth(); const navigate = useNavigate(); const [status, setStatus] = useState(null);
  useEffect(() => { let active = true; const refresh = () => getEmployeeStatus().then((data) => active && setStatus(data)).catch(() => {}); refresh(); const timer = setInterval(refresh, 3000); return () => { active = false; clearInterval(timer); }; }, []);
  const finish = () => { logout(); navigate('/'); }; const submitted = status?.submission_status === 'Submitted'; const decision = status?.decision;
  return <main className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><div><p className="font-extrabold text-slate-900">Employee Attrition Intelligence</p><p className="text-xs text-slate-500">Employee workspace</p></div><button onClick={finish} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><LogOut size={16}/> Logout</button></div></header><section className="mx-auto max-w-6xl px-5 py-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-indigo-600">Employee dashboard</p><h1 className="mt-1 text-3xl font-black text-slate-950">Welcome, {status?.name || user.name}</h1><p className="mt-2 text-sm text-slate-500">{status?.employee_id || user.employeeId} · {status?.email || user.email}</p></div>{submitted ? <Link to="/employee/status" className="rounded-xl border border-indigo-200 bg-white px-5 py-3 text-sm font-bold text-indigo-700">View Submission Status</Link> : <Link to="/employee/assessment" className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white">Start Assessment</Link>}</div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Assessment Status', submitted ? 'Submitted' : 'Not Submitted'], ['Selected HR', status?.selected_hr_name || 'Not selected'], ['Review Status', status?.review_status || 'Pending'], ['Final Decision', decision || 'Awaiting HR Decision']].map(([label, value]) => <div className="border border-slate-200 bg-white p-5 shadow-sm" key={label}><p className="text-xs font-bold uppercase tracking-widest text-slate-400">{label}</p><p className="mt-3 text-lg font-black text-slate-900">{value}</p></div>)}</div>{decision && <div className={`mt-6 border-l-4 p-5 ${decision === 'Continued' ? 'border-emerald-500 bg-emerald-50' : 'border-rose-500 bg-rose-50'}`}><p className="text-sm font-black uppercase tracking-widest text-slate-700">HR Review Completed</p><p className="mt-2 font-bold text-slate-900">Your employment has been {decision.toLowerCase()}.</p>{decision === 'Discontinued' && <p className="mt-1 text-sm text-slate-600">WhatsApp notification status: {status?.notification_status || 'pending'}.</p>}</div>}<div className="mt-8 border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-extrabold text-slate-900">Assessment timeline</h2><div className="mt-6 grid gap-4 sm:grid-cols-6">{['Assessment Submitted','Sent to HR','Received','Under Review','Reviewed','Decision Made'].map((item, index) => <div key={item} className="flex gap-3 sm:block"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-black ${submitted && (decision || index < 4) ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-400'}`}>{index + 1}</span><p className="pt-1 text-sm font-bold text-slate-600">{item}</p></div>)}</div></div></section></main>;
}
