import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import HRLayout from '../components/HRLayout';
import { getEmployeesForHR } from '../services/api';

export default function HREmployees() {
  const [employees, setEmployees] = useState([]); const [search, setSearch] = useState(''); const [risk, setRisk] = useState('All'); const [status, setStatus] = useState('All');
  useEffect(() => { let active = true; const refresh = () => getEmployeesForHR().then((records) => active && setEmployees(records)).catch(() => {}); refresh(); const timer = setInterval(refresh, 3000); return () => { active = false; clearInterval(timer); }; }, []);
  const visible = employees.filter((employee) => `${employee.employee?.name || ''}${employee.employee_id}`.toLowerCase().includes(search.toLowerCase())).filter((employee) => risk === 'All' || employee.risk === risk).filter((employee) => status === 'All' || employee.review_status === status);
  return <HRLayout><div className="mx-auto max-w-7xl px-5 py-8 lg:px-10"><p className="text-sm font-bold text-indigo-600">Review queue</p><h1 className="mt-1 text-3xl font-black text-slate-950">Employees Submitted to Me</h1><div className="mt-7 grid gap-3 md:grid-cols-[1fr_180px_180px]"><input className="custom-input rounded-xl px-4 py-3 text-sm" placeholder="Search name or employee ID" value={search} onChange={(event) => setSearch(event.target.value)} /><select className="custom-input rounded-xl px-4 py-3 text-sm" value={risk} onChange={(event) => setRisk(event.target.value)}><option>All</option><option>Low</option><option>Medium</option><option>High</option></select><select className="custom-input rounded-xl px-4 py-3 text-sm" value={status} onChange={(event) => setStatus(event.target.value)}><option>All</option><option>Pending</option><option>Under Review</option><option>Reviewed</option></select></div><div className="mt-5 overflow-x-auto border border-slate-200 bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><tr>{['Employee','Job Role','Prediction','Risk','Review Status','Decision','Action'].map((heading) => <th className="px-5 py-4" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{visible.map((record) => <tr key={record.employee_id}><td className="px-5 py-4"><p className="font-extrabold text-slate-800">{record.employee?.name}</p><p className="text-xs text-slate-400">{record.employee_id}</p></td><td className="px-5 py-4 text-slate-600">{record.features?.JobRole}</td><td className="px-5 py-4 font-bold">{record.prediction}</td><td className="px-5 py-4 font-bold">{record.risk}</td><td className="px-5 py-4 text-slate-600">{record.review_status}</td><td className="px-5 py-4 text-slate-600">{record.review?.decision || 'Awaiting decision'}</td><td className="px-5 py-4"><Link to={`/hr/employees/${record.employee_id}`} className="rounded-lg bg-indigo-50 px-3 py-2 text-xs font-bold text-indigo-700">Review</Link></td></tr>)}</tbody></table>{!visible.length && <p className="p-8 text-center text-sm text-slate-500">No employees match these filters.</p>}</div></div></HRLayout>;
}
