import React from 'react';
import { ArrowRight, CheckCircle2, ShieldCheck, Users } from 'lucide-react';
import { Link } from 'react-router-dom';

const steps = ['Employee Information', 'ML Analysis', 'Risk Insight', 'HR Review', 'Final Decision'];
export default function LandingPage() {
  return <main className="min-h-screen bg-ambient-pattern px-5 py-8 sm:px-10 lg:px-16">
    <header className="mx-auto flex max-w-7xl items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-indigo-600 text-white"><ShieldCheck /></div><div><p className="font-extrabold text-slate-900">Employee Attrition Intelligence</p><p className="text-xs text-slate-500">Workforce Risk & Retention Insights</p></div></div><span className="hidden text-xs font-bold uppercase tracking-wider text-emerald-600 sm:block">Secure workforce workflow</span></header>
    <section className="mx-auto grid max-w-7xl gap-14 pb-16 pt-20 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:pt-28"><div><p className="mb-4 text-sm font-bold uppercase tracking-[.18em] text-indigo-600">A clearer path from signal to support</p><h1 className="max-w-3xl text-5xl font-black tracking-tight text-slate-950 sm:text-6xl">Make workforce decisions with context, care, and confidence.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">A focused workspace where employees share the right information and HR teams turn model insights into thoughtful retention decisions.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/employee/login" className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-6 py-3.5 text-sm font-bold text-white shadow-lg shadow-indigo-600/20">Employee Portal <ArrowRight size={17} /></Link><Link to="/hr/login" className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-6 py-3.5 text-sm font-bold text-slate-800">HR Portal <ArrowRight size={17} /></Link></div></div><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-card"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Workflow</p><h2 className="mt-1 text-xl font-extrabold text-slate-900">From information to action</h2></div><Users className="text-indigo-500" /></div><div className="space-y-3">{steps.map((step, index) => <div key={step} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-slate-50 px-4 py-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-indigo-100 text-xs font-black text-indigo-700">0{index + 1}</span><span className="text-sm font-bold text-slate-700">{step}</span>{index < steps.length - 1 && <CheckCircle2 className="ml-auto text-emerald-500" size={17} />}</div>)}</div></div></section>
  </main>;
}
