import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, LockKeyhole, ShieldCheck } from 'lucide-react';
import FormInput from '../components/FormInput';
import { useAuth } from '../context/AuthContext';
import { HR_ACCOUNTS } from '../data/mockData';
import { loginEmployee, loginHR } from '../services/api';
export default function PortalLogin({ role }) { const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const { login } = useAuth(); const navigate = useNavigate(); const employee = role === 'employee';
 const submit = async (event) => { event.preventDefault(); setError(''); try { const user = employee ? await loginEmployee(form.email, form.password) : await loginHR(form.email, form.password, HR_ACCOUNTS); login(user, role); navigate(`/${role}/dashboard`); } catch (err) { setError(err.message); } };
 return <main className="min-h-screen bg-slate-50 px-5 py-10"><div className="mx-auto max-w-md"><Link to="/" className="mb-10 inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Back to portals</Link><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-card"><div className="mb-7 flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-600 text-white"><ShieldCheck/></div><h1 className="text-2xl font-black text-slate-950">{employee ? 'Employee Portal' : 'HR Portal'} login</h1><p className="mt-2 text-sm text-slate-500">{employee ? 'Access your assessment and review status.' : 'Review workforce insights and employee submissions.'}</p><form onSubmit={submit} className="mt-7 space-y-4">{!employee && <FormInput label="Name" name="name" value={form.name} onChange={(e) => setForm({...form, name:e.target.value})} placeholder="Priya Sharma" required/>}<FormInput label="Email" name="email" type="email" value={form.email} onChange={(e) => setForm({...form, email:e.target.value})} placeholder={employee ? 'you@example.com' : 'priya@demo.hr'} required/><FormInput label="Password" name="password" type="password" value={form.password} onChange={(e) => setForm({...form, password:e.target.value})} placeholder="demo123" required/>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</p>}<button className="flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-3.5 text-sm font-bold text-white"><LockKeyhole size={16}/> Login</button></form>{employee && <Link to="/employee/signup" className="mt-5 block text-center text-sm font-bold text-indigo-600">Create Account</Link>}{!employee && <p className="mt-5 text-center text-xs text-slate-400">Demo HR password: demo123</p>}</div></div></main>; }
